# Generated by Django 5.2.2 on 2025-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productrequest",
            name="username",
            field=models.CharField(default="Anonymous", max_length=150),
        ),
    ]
