# Generated by Django 5.2.1 on 2025-06-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_item"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="ProductRequest",
        ),
    ]
