# Generated by Django 5.2.7 on 2025-10-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reference_code",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
