# Generated by Django 5.2.7 on 2025-10-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_order_reference_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="items",
            name="image",
        ),
        migrations.AddField(
            model_name="items",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
