# Generated by Django 5.2.7 on 2025-10-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_items_image_items_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="sizes",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated sizes like M,L,XL",
                max_length=100,
            ),
        ),
    ]
