name: Code Quality and Security Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black bandit safety isort coverage pytest

      - name: Run black check
        run: black --check .

      - name: Run isort check
        run: isort . --check-only

      - name: Run flake8
        run: flake8 .

      - name: Run bandit
        run: bandit -r .

      - name: Run safety
        run: safety check

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report
